/**
 * Английские реплики персонажа по классам.
 *
 * Параллель русскому набору (`ru.ts`): та же структура и моменты броска. Перевод
 * вольный — мы сохраняем характер и юмор класса, а не буквальность.
 */

import type { ClassPhrases, PhrasesByClass } from './types.ts'

/** Нейтральный набор — когда класс героя не выбран. */
export const DEFAULT_PHRASES_EN: ClassPhrases = {
  shake: ['Shaking the dice…', 'Rattling the bones in my palms…', 'Warming up the dice with a shake…'],
  release: ['The dice are spinning… come on…', 'Rolling, waiting for the result…', 'Frozen in anticipation…'],
  epic: ['All my strength — into this roll!', 'Something great is brewing…', 'The air rings with tension…'],
  success: ['Critical success! A twenty!', 'Natural 20 — perfect!', 'Crit! It does not get better!'],
  fail: ['Critical failure… a one.', 'Natural 1 — what rotten luck.', 'A miss! The dice let me down.'],
}

/** Реплики по классам. Тот же характер и юмор, что и в русском наборе. */
export const PLAYER_PHRASES_EN: PhrasesByClass = {
  barbarian: {
    shake: [
      'I SHAKE HARD AND ANGRY!',
      'I shake them till the bones scream!',
      'Clenched in my fist, shaking with all my might!',
      'I shake, and I feel the rage rising!',
      'I explode them with a shake — let them fear!',
      'I shake, and a war cry already rings in my head!',
      'I shake, and picture myself crushing my foes!',
      'I shake, and my blood boils for the coming fight!',
      'I shake, and feel the strength fill me!',
    ],
    release: [
      'WAAARGH! How high will you roll?!',
      'HOW MANY WILL I CRUSH?!',
      'Here they go! Come on, tribe, don\u2019t fail me!',
      'They fly, and I already see myself crushing my foes!',
      'They roll, and I feel the rage hit its peak!',
      'They fly like hammers of war — I await a crushing blow!',
      'They roll, and I hope for a crushing result!',
      'They fly, as the bones of my enemies will fly!',
      'They roll, and I already taste victory!',
    ],
    epic: [
      'WAAAAAAAAAARGH!!!',
      'FOR THE HOOOOORDE!!!',
    ],
    success: [
      'CRIT! ENEMIES, PRAY!',
      'A TWENTY! I\u2019LL CRUSH IT ALL!',
      'NATURAL 20 — I\u2019LL SMASH IT TO SPLINTERS!',
      'RAGE ROLLED A CRIT!',
    ],
    fail: [
      'A MISS! I\u2019LL GRIND THIS DIE TO DUST!',
      'Natural 1… now I\u2019m even angrier!',
      'Missed — but my fury only grows!',
    ],
  },
  bard: {
    shake: [
      'Shaking the dice to the rhythm of the chorus…',
      'Rattling them to the ring of my lute…',
      'Hey-ho, shake-and-go…',
      'I shake, and verses of a song are already born in my head…',
      'I rattle them, and feel inspiration…',
      'I spin them, and a melody already plays in my head…',
      'I shake, and picture the crowd cheering…',
      'I rattle them, and feel the stage energy rising…',
      'I spin them, already savoring the applause…',
    ],
    release: [
      'A drumroll… the dice take flight!',
      'They spin like a ballad\u2019s finale…',
      'Hush, audience — here comes the climax!',
      'They fly, and I already see the crowd in awe!',
      'They spin, and I feel the stage energy hit its peak!',
      'They fly, and I hope for an ovation!',
      'They spin, and I already savor the cheering!',
    ],
    epic: [
      'They’ll sing legends of this roll!',
      'Let the whole world hear this song!',
      'Here comes the most dramatic moment of the ballad!',
      'To roll or not to roll — that is the question!',
    ],
    success: [
      'Crit! The hall applauds — a twenty!',
      'Natural 20 — the ballad\u2019s finale lands!',
      'Ovation! That was the perfect note!',
      'Twenty! This song will become a legend!',
    ],
    fail: [
      'A one… a false note, alas.',
      'Natural 1 — the audience winces.',
      'A miss! The lute twangs pitifully.',
      'Oof… I\u2019ve lost the rhythm.',
    ],
  },
  cleric: {
    shake: [
      'Shaking the dice with a prayer on my lips…',
      'Rattling them, beseeching the god of dice…',
      'Sanctifying the rolls, shaking them in my palm…',
      'I shake, and feel the blessing…',
      'I rattle them, and hear the soft voice of the divine…',
      'I spin them, and He watches over me…',
      'I shake, and picture divine power filling me…',
      'I rattle them, and feel the sacred energy rising…',
      'I spin them, trusting in divine aid…',
    ],
    release: [
      'Fly! Let the will of the heavens be done…',
      'They spin in fate\u2019s hand — I await an omen…',
      'Almighty, reveal the number…',
      'They fly, and I already see divine power at work!',
      'They spin, and I feel the blessing hit its peak!',
      'They fly, and I hope for divine aid!',
      'They spin, and I already await a miracle!',
      'They fly, and I trust the gods heard my prayer!',
      'All is the will of the Lord!',
    ],
    epic: [
      'Show me a miracle, Almighty!',
      'Gods, I pay my tithe! Pretty please!',
    ],
    success: [
      'A twenty! The heavens blessed the roll!',
      'Crit! The will of the divine is done!',
      'Natural 20 — a miracle made manifest!',
      'Hallelujah! The gods have heard me!',
    ],
    fail: [
      'A one… a test of faith sent to me.',
      'Natural 1 — the heavens stayed silent.',
      'A miss… so there is a higher plan.',
      'The gods turned away… I accept it humbly.',
    ],
  },
  druid: {
    shake: [
      'Shaking the dice like seeds in my palms…',
      'Rattling them to the whisper of leaves…',
      'I clatter the bones like a handful of acorns…',
      'I shake, and feel the bond with nature…',
      'I rattle them, and hear the voices of spirits…',
      'I spin them, and they seem to drink in the earth\u2019s power…',
    ],
    release: [
      'They roll like stones in a mountain stream…',
      'Nature decides — I await its word…',
      'I freeze, listening to what the spirits say…',
      'They fly, and I already feel nature at work!',
      'They fly, and I hope for the spirits\u2019 favor!',
    ],    epic: [
      'I AM GROOOOOOT!',
    ],    success: [
      'Twenty! Nature itself is on my side!',
      'Crit! The spirits rejoice with me!',
      'Natural 20 — wild luck!',
      'The elements answered — a perfect roll!',
    ],
    fail: [
      'A one… nature is fickle today.',
      'Natural 1 — the spirits turned away.',
      'A miss… not the season for luck, it seems.',
      'Alas, the roots failed me.',
    ],
  },
  fighter: {
    shake: [
      'Shaking the dice with a practiced motion…',
      'Rattling them — one, two, by the book…',
      'Warming up the dice before the roll…',
      'I shake, already drilling tactics in my head…',
      'I rattle them, and feel my battle focus sharpen…',
      'I spin them, already picturing a clean strike…',
    ],
    release: [
      'They fly straight and true — I await the hit…',
      'They roll toward the target… at the ready!',
      'I stand at attention, awaiting the outcome…',
      'They fly, and I already see myself crushing my foes!',
      'They fly, and I hope for a precise strike!',
    ],
    epic: [
      'Everything I trained for — for this strike!',
      '…',
      'Either I punch through this armor, or order a coffin!',
      'THIS IS SPARTAAAAAAAA!!!',
    ],
    success: [
      'A twenty! A strike dead on target!',
      'Crit! The training paid off!',
      'Natural 20 — a textbook hit!',
      'A clean crit, straight by the book!',
    ],
    fail: [
      'A one… a misfire at the worst moment.',
      'Natural 1 — my hand wavered.',
      'A miss! Pull yourself together, soldier.',
      'Wide… the debrief comes later.',
    ],
  },
  monk: {
    shake: [
      'Shaking the dice in the flow of breath…',
      'I rattle them — and my mind is calm…',
      'I spin them slowly, centering my chi…',
      'I shake, and feel energy flow through me…',
      'I rattle them, and hear my inner voice…',
      'I spin them, meditating, awaiting a harmonious result…',
    ],
    release: [
      'They roll in perfect balance…',
      'Frozen in zen, I await what the flow reveals…',
      'Ommm… the dice spin, and I am calm…',
      'Bruce Lee unleashed a thousand strikes!',
    ],
    epic: [
      'All my chi gathered into this instant…',
      'I’ve honed this strike my whole life!',
      'Kiiiiiiiiyaaaaaaa!!!',
      'Banzai!!!',
      '拳必殺, Ikken HissAAAAAAAATSUUUUUUUUUUU!!!',
    ],
    success: [
      'Twenty. Flow and body — as one.',
      'Crit. Perfect balance of chi.',
      'Natural 20 — harmony achieved.',
      'The thousand-fist strike — dead on target.',
      'Zen itself would cry out in delight — a crit!',
      'Bruce Lee himself rolled this crit!',
    ],
    fail: [
      'A one. My breath faltered for an instant.',
      'Natural 1 — the balance is broken.',
      'A miss. I return to the start of the path.',
      'The flow is gone… I accept it calmly.',
    ],
  },
  paladin: {
    shake: [
      'Shaking the dice in the name of my oath…',
      'Rattling them, calling upon the light…',
      'I spin them with a hand guided by duty…',
      'I shake, and feel sacred power filling me…',
      'I rattle them, and hear the voice of conscience…',
      'I spin them, picturing how I fulfill my vow…',
    ],
    release: [
      'They fly for the glory of justice — I await judgment…',
      'They spin beneath the gaze of the heavens…',
      'I freeze: let the light judge the righteous cause…',
      'They fly — and who awaits their punishment?',
    ],
    epic: [
      'May the Force be with me!',
      'Let the will of the heavens be done, and my foe shall fall!',
      'Judgment is at hand!',
      'Puuunishment!!!',
      'Hold the line! The enemy must fall!',
      'Stand to the death!!!',
    ],
    success: [
      'A twenty! A reward for keeping my oath!',
      'Crit! Justice has triumphed!',
      'Natural 20 — the oath is fulfilled!',
      'The heavens passed their verdict — a crit!',
    ],
    fail: [
      'A one… the light tests my resolve.',
      'Natural 1 — but the oath is unbroken.',
      'A miss… I will atone for it in battle.',
      'I stumbled, but I won\u2019t stray from the path.',
    ],
  },
  ranger: {
    shake: [
      'Shaking the dice quietly, so as not to scare off luck…',
      'Rattling them, biding the moment and the wind…',
      'I spin them, reading the trail of the number I need…',
      'I shake, and feel the quarry drawing near…',
      'I rattle them, and hear the rustle of victory…',
      'I spin them, picturing a clean hit on target…',
    ],
    release: [
      'They fly like an arrow to the mark…',
      'They roll to the target — I hold my breath…',
      'I freeze: where will they land — bullseye?',
      'They fly, and I already see myself hitting the mark!',
      'They roll, and I hope for a true result!',
    ],
    epic: [
      'I’ve tracked this moment the entire hunt…',
      'The arrow of fate on the string… I will not miss!',
    ],
    success: [
      'Twenty! Right in the bullseye!',
      'Crit! This arrow never misses!',
      'Natural 20 — a blind shot, and dead on!',
      'A perfect trail — straight to the ten!',
    ],
    fail: [
      'A one… the wind pulled the roll astray.',
      'Natural 1 — I lost the trail.',
      'A miss… the quarry slipped away.',
      'Wide… I\u2019ll hunt down luck another time.',
    ],
  },
  rogue: {
    shake: [
      'Shaking the dice… no one\u2019s watching, right?',
      'Rattling them deftly, with a couple of sly moves…',
      'I spin them in my palm — clean, no traces…',
      'I shake quietly, drawing no attention…',
      'I shake them — unseen and skilled…',
      'I twist and turn them, eager to fool everyone…',
    ],
    release: [
      'Off they go, and I almost know the outcome…',
      'They roll unnoticed — I await my cut…',
      'I freeze in the shadows, awaiting the right deal…',
      'They fly, and I hope for some luck…',
      'They roll, and I pray to fortune…',
      'I freeze, secretly hoping for luck…',
    ],
    epic: [
      'All or nothing — the greatest con of my life!',
      'I bet everything on this roll!',
    ],
    success: [
      'A twenty… not that I ever doubted it.',
      'Crit. Tweaked it — and no one noticed.',
      'Natural 20 — clean work.',
      'Spot on. Luck loves the nimble.',
      'Crit! Fortune is on my side.',
      'Sleight of hand and no cheating at all!',
    ],
    fail: [
      'A one… not now of all times!',
      'Natural 1 — did someone swap the dice?',
      'A miss… I\u2019ll pretend it was on purpose.',
      'A slip-up. I vanish into the shadows.',
    ],
  },
  sorcerer: {
    shake: [
      'Shaking the dice — and magic sparks within them…',
      'Rattling them, wild power surging…',
      'I spin them — sparks crackle between my fingers…',
      'I shake, and feel the energy building…',
      'I rattle them, and the magic strains to break free…',
    ],
    release: [
      'They fly, wreathed in wild magic — I await the flash…',
      'They spin in a vortex of power… what will come up?',
      'I freeze: blood will decide — I await the outcome…',
      'They fly, and I feel their power…',
      'They spin, and I hope for a mighty result…',
    ],
    epic: [
      'WILD MAGIC BURSTS OUT OF ME!',
      'Ahahahahahaa! Magic goes BOOM!',
      'I don’t know what’ll happen… but it’ll be MAGNIFICENT!',
    ],
    success: [
      'Twenty! Wild magic surged to the target!',
      'Crit! The power in my blood held true!',
      'Natural 20 — the elements obeyed!',
      'A flash! A perfect discharge of power!',
    ],
    fail: [
      'A one… the magic went haywire.',
      'Natural 1 — a wild surge jinxed the roll.',
      'A miss! The power slipped out of control.',
      'Sparks to nowhere… it happens.',
      'Such power sometimes turns against you…',
    ],
  },
  warlock: {
    shake: [
      'Shaking the dice, whispering to my patron…',
      'Rattling them by the terms of the great bargain…',
      'My patron bade me shake — so I shake…',
      'I shake, and feel its presence…',
      'I rattle them, and hear its soft voice…',
      'I spin them, and it watches over me…',
    ],
    release: [
      'They fly by the will of the pact — I await the price…',
      'They spin in the dark, the patron watching…',
      'I freeze: what will the bargain inscribe for me?',
      'They fly, and I feel its power…',
      'They spin, and I hope for its favor…',
      'I freeze, dreading its wrath in my heart…',
    ],
    epic: [
      'Patron, I call upon the full power of the pact!',
      'For this roll I’m ready to pay any price!',
      'Boss, I’ll earn it! Just give me that twenty!',
      'Boss, if I die, the contract is void!',
    ],
    success: [
      'Twenty! The patron is pleased with the deal.',
      'Crit! The pact has borne fruit.',
      'Natural 20 — the price paid off.',
      'The patron smiled upon me — a crit!',
    ],
    fail: [
      'A one… the patron is displeased.',
      'Natural 1 — the price of the deal rises.',
      'A miss… I\u2019ll have to give even more.',
      'The pact turned against me…',
    ],
  },
  wizard: {
    shake: [
      'Shaking the dice, having reckoned the odds…',
      'Rattling them strictly by calculation…',
      'I spin them, verifying each rotation…',
      'I shake, and theories already form in my head…',
      'I rattle them, mentally running through the options…',
    ],
    release: [
      'They fly per the formulas — I await confirmation…',
      'They spin per theory… let\u2019s check it now…',
      'I freeze: the experiment is underway, I await the result…',
      'They fly, and I analyze their motion…',
      'They spin, and I hope for a favorable outcome…',
      'I freeze, conjectures already forming in my head…',
    ],
    epic: [
      'Merlin’s beard!',
      'The climax of all my calculations!',
      'I’ve calculated everything! I hope…',
    ],
    success: [
      'Twenty! The probability lined up perfectly.',
      'Crit! The calculation proved flawless.',
      'Natural 20 — hypothesis confirmed!',
      'The experiment succeeded — maximum on the die!',
    ],
    fail: [
      'A one… a statistical outlier, no doubt.',
      'Natural 1 — an unfortunate margin of error.',
      'A miss… I\u2019ll revise the model.',
      'Minimum on the die… unlikely, yet here it is.',
    ],
  },
}
